---
name: Deploy install-operators Image

on:
  push:
    branches: ['main']
    
  workflow_dispatch:

env:
  REGISTRY: quay.io
  ORG: cspi-qe-images
  QUAY_SERVICE_ACCOUNT_USER: cspi-qe-images+github
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.QUAY_SERVICE_ACCOUNT_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/ocp-ci-install-operators

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./install-operators/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
